DEP Remove silverstripe/campaign-admin
silverstripe/recipe-cms pull request #93
Opened 2024-11-20 05:20 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/884

2024-11-26 21:37 UTC, GuySartorelli approved these changes
LGTM, will merge when the recipe-sink PR is ready to merge.

2024-11-26 22:03 UTC, GuySartorelli requested changes
Actually just realised - there's a reference still in `phpunit.xml.dist` that needs to be removed.

2024-11-27 00:47 UTC, emteknetnz commented
Updated

2024-11-27 21:14 UTC, GuySartorelli approved these changes

2024-11-28 01:45 UTC, merged